config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'
  resources "entries"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def index
    @entries = Entry.all
  end

  def show
    @entry = Entry.find(params[:id])
  end

  def new
  end

  def create
    entry_params = params["entry"].permit("title", "contents")
    entry = Entry.create(entry_params)
    redirect_to(entry_path(entry))
  end

  def edit
    @entry = Entry.find(params[:id])
  end

  def update
    entry_params = params["entry"].permit("title", "contents")
    entry = Entry.find(params["id"])
    entry.update(entry_params)
    redirect_to(entry_path(entry))
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @websites = [
      ["http://railsgirls.com", "Rails Girls"],
      ["https://en.wikibooks.org/wiki/Ruby_Programming", "Wikibooks"],
      ["http://guides.rubyonrails.org", "Ruby on Rails Guides"],
    ]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/entries/edit.html.erb
<%= form_for(@entry) do |form| %>
  <p><%= form.label("title") %></p>
  <p><%= form.text_field("title") %></p>
  <p><%= form.label("contents") %></p>
  <p><%= form.text_area("contents") %></p>
  <p><%= form.submit %></p>
<% end %>
<p><%= link_to("Back to all entries", entries_path) %></p>

app/views/entries/index.html.erb
<h1>Hello world :)</h1>
<h1>My Rails Girls Diary</h1>
	<div>
    <%= link_to("Nowy wpis", new_entry_path) %>
    <% @entries.each do |entry| %>
    <h2><%= link_to(entry.title, entry_path(entry)) %></h2>
      <p><%= entry.date %></p>
      <p><%= entry.contents %></p>
    <% end %>
	</div>

app/views/entries/new.html.erb
<%= form_for(Entry.new) do |form| %>
  <p><%= form.label("title") %></p>
  <p><%= form.text_field("title") %></p>
  <p><%= form.label("contents") %></p>
  <p><%= form.text_area("contents") %></p>
  <p><%= form.submit %></p>
<% end %>
<p><%= link_to("Back to all entries", entries_path) %></p>

app/views/entries/show.html.erb
<div>
  <h2><%= @entry.title %></h2>
  <p><%= @entry.date %></p>
  <p><%= @entry.contents %></p>
  <p><%= link_to("Edytuj", edit_entry_path(@entry)) %> </p>
  <p><%= link_to("Powrót", entries_path) %></p>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html>
<head>
	<title>My Little Webapp: Coding Is Magic</title>
	<meta charset='UTF-8' />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/welcome/index.html.erb
	<div>
		<h1>My favourite websites</h1>
		<ul>
      <% @websites.each do |url, name| %>
        <li><a href="<%= url %>"><%= name %></a></li>
      <% end %>
		</ul>
	</div>
	<img src='http://railsgirls.com/images/rg-warsaw.png' />

	<form action='/'>
		<p><input name='title' type='text' placeholder='Title'></p>
		<p><textarea name='title' placeholder='Content'></textarea></p>

		<p><input type="submit" value="Create"></p>
	</form>
	<p><a href='#'>Back</a></p>